export { sparql } from '@tpluscode/rdf-string'
export { DELETE, DeleteInsertQuery as DeleteInsert, DeleteData } from './lib/DeleteBuilder.js'
export { INSERT, InsertQuery as Insert, InsertData } from './lib/InsertBuilder.js'
export { ASK, AskQuery as Ask } from './lib/AskBuilder.js'
export { DESCRIBE, DescribeQuery as Describe } from './lib/DescribeBuilder.js'
export { CONSTRUCT, ConstructQuery as Construct } from './lib/ConstructBuilder.js'
export { SELECT, SelectQuery as Select } from './lib/SelectBuilder.js'
export { WITH } from './lib/WithBuilder.js'
export { prefixes } from '@tpluscode/rdf-string'
export type { SparqlTemplateResult } from '@tpluscode/rdf-string'
