name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npx typedoc
    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@2.0.0
      env:
        EMAIL: tomasz@t-code.pl
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: docs/
